server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  # ðŸ‘‡ ESTO ES LO QUE TE FALTABA
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        # ========= AUTH SERVICE =========
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0   # no quitamos nada, el auth-service ya usa /api/auth/...

        # ========= QUIZ SERVICE =========
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quiz/**
          filters:
            - StripPrefix=0

        # ========= GAME SERVICE =========
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/game/**
          filters:
            - StripPrefix=0

        # ========= FEEDBACK SERVICE =========
        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/api/feedback/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
